MTGWatcher/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MTGWatcher.DAL;
using MTGWatcher.Models;
using Newtonsoft.Json;
using System.IO;
using System.Data.Entity.Validation;
using System.Linq.Dynamic;
using System.IO.Compression;
using Microsoft.VisualBasic.FileIO;

namespace MTGWatcher.Controllers
{
    public class CardsController : Controller
    {
        private MTGWatcherContext db = new MTGWatcherContext();
        private static float RefreshSetsProgress { get; set; }
        // GET: Cards
        public ActionResult Index()
        {

            var model = new CardListViewModel();
            model.Results = db.Cards.ToList();
            model.ResultCount = model.Results.Count;
            model.PageSize = 25;
            model.Page = 1;
            model.SortField = "Name";
            model.SortDir = "DESC";
            model.Filter = "";

            return View(model);
        }
        [HttpPost]
        public ActionResult Index(CardListViewModel model,string cardSearch)
        {

            if (model.Page == 0)
            {
                model.Results = db.Cards.ToList();
                model.ResultCount = model.Results.Count;
                model.PageSize = 25;
                model.Page = 1;
                model.SortField = "Name";
                model.SortDir = "DESC";
                model.Filter = "";
            }

            var filterCards = new List<Card>();
            //var results = FilterCards(model);
            if (!string.IsNullOrEmpty(cardSearch))
            {
                filterCards = db.Cards.Where(o => o.Name.Contains(cardSearch) || o.Text.Contains(cardSearch)).ToList();

                if (filterCards.Count == 1)
                    return RedirectToAction("Details", new { id = filterCards.FirstOrDefault().CardId });
            }

            model.ResultCount = db.Cards.Count();
            model.PageSize = 25;

            if (string.IsNullOrEmpty(model.SortField) || string.IsNullOrEmpty(model.SortDir))
                model.Results = db.Cards.OrderBy("Name", "DESC").Skip((model.Page - 1) * model.PageSize).Take(model.PageSize).ToList();
            else
                model.Results = db.Cards.OrderBy(model.SortField, model.SortDir).Skip((model.Page - 1) * model.PageSize).Take(model.PageSize).ToList();

            return View(model);
        }

        // GET: Cards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            if(string.IsNullOrEmpty(card.ImageUrl)) card.ImageUrl = CardImageUrlFind(card.Name);

            var response = RequestHelper.mkmRequest("https://www.mkmapi.eu/ws/v2.0/output.json/products/" + card.MkmProductId);
            var product = JsonConvert.DeserializeObject<Dictionary<string, Product>>(response);
            card.mkmProduct = product.FirstOrDefault().Value;

            return View(card);
        }

        // GET: Cards/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CardId,Name,Cmc")] Card card)
        {
            if (ModelState.IsValid)
            {
                db.Cards.Add(card);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(card);
        }

        // GET: Cards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CardId,Name,Cmc")] Card card)
        {
            if (ModelState.IsValid)
            {
                db.Entry(card).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(card);
        }

        // GET: Cards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            Card card = db.Cards.Find(id);
            db.Cards.Remove(card);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult RefreshCards()
        {
            try
            {
                var cards = JsonConvert.DeserializeObject<Dictionary<string, JsonCard>>(System.IO.File.ReadAllText(HttpContext.Server.MapPath("~/StaticJson/AllCards.json")));
                var dbCards = cards.Select(x => new Card() {
                    Name = x.Value.name ,
                    Cmc = x.Value.cmc,
                    ColorIdentity = x.Value.colorIdentity,
                    Colors = x.Value.colors,
                    ManaCost = x.Value.manaCost ,
                    Text = x.Value.text ,
                    Power = x.Value.power,
                    Toughness = x.Value.toughness,
                    Types = x.Value.types}).ToList();
                db.Cards.AddRange(dbCards);
                db.SaveChanges();

            }
            catch (Exception e)
            {
              
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult RefreshSets()
        {

            try
            {
                var sets = JsonConvert.DeserializeObject<Dictionary<string, JsonSet>>(System.IO.File.ReadAllText(HttpContext.Server.MapPath("~/StaticJson/AllSets.json")));
                RefreshSetsProgress = 0;
                float i = 0;
                foreach (var item in sets)
                {
                    i++;
                    RefreshSetsProgress=  i/(float)sets.Count;
                    db.Sets.Add(new SetModel() { Name = item.Value.name , Code = item.Value.code,ReleaseDate = item.Value.releaseDate});
                    db.SaveChanges();
                    foreach (var card in item.Value.cards)
                    {                   
                        
                        card.SetId = db.Sets.Where(x => x.Code == item.Value.code).FirstOrDefault().SetId;
                        db.Cards.Add(card);
                    }
                }

                db.SaveChanges();
                
            }
            catch (Exception e)
            {
                
            }

            return RedirectToAction("Index");
        }

        public JsonResult RefreshProgress()
        {
            
            return Json(new { message="OK" ,data = RefreshSetsProgress}, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Autocomplete(string term)
        {
            var filteredItems = db.Cards.Where(item => item.Name.Contains(term));
            var nameList = filteredItems.Select(x => x.Name).ToList();
            return Json(nameList, JsonRequestBehavior.AllowGet);
        }

        private string CardImageUrlFind(string cardName)
        {
            var urlMultiverse = string.Format("http://gatherer.wizards.com/pages/search/default.aspx?name=+[{0}]",Url.Encode(cardName));
            var request = WebRequest.Create(urlMultiverse);
            var resp = request.GetResponse();
            var urlResp = resp.ResponseUri.ToString();
            var index = urlResp.IndexOf("multiverseid=");
            if (index == -1) return null;
            int multiverseid;
            if (!int.TryParse(urlResp.Substring(index + 13, urlResp.Length - index - 13), out multiverseid)) return null;
            string urlImage =string.Format("http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid={0}&type=card", multiverseid);
            resp.Dispose();
            return string.IsNullOrEmpty(urlImage)?null:urlImage;
        }


        public ActionResult RefreshMkmProducts()
        {
            var timestamp = DateTime.Now.ToString("yyyyMMddhhmmss");
            var rawString64 = JsonConvert.DeserializeObject<ProductList>(RequestHelper.mkmRequest("https://www.mkmapi.eu/ws/v2.0/output.json/productlist")).productsfile;
            var gzip = Convert.FromBase64String(rawString64);
            System.IO.File.WriteAllBytes(HttpContext.Server.MapPath("~/MkmFiles/mkmProduct" + timestamp + ".gzip"), gzip);

            //Uncompress to readable csv file

MTGWatcher/Views/Cards/Create.cshtml
@model MTGWatcher.Models.Card

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Card</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CardId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cmc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cmc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cmc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MTGWatcher/Views/Cards/Delete.cshtml
@model MTGWatcher.Models.Card

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Card</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cmc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cmc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MTGWatcher/Views/Cards/Details.cshtml
@model MTGWatcher.Models.Card

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div class="row">
    <div class="col-lg-12">
        <h4>@Html.DisplayFor(model => model.Name)</h4>
        <hr />
    </div>
    <div class="col-lg-4">
        <img class="img-responsive" src="@Model.ImageUrl" alt="@Model.ImageUrl" />
    </div>
    <div class="col-lg-8">
        <h4>@Html.DisplayFor(model => model.Name)</h4>
        <p>@Model.Text</p>
        <p><i>"@Model.Flavor"</i></p>
        <p>artist : @Model.Artist</p>
    </div> 
    <div class="col-lg-8">
        <h4>Avergage Price : @Model.mkmProduct.priceGuide.AVG €</h4>
        <h4>Lowest Price : @Model.mkmProduct.priceGuide.LOW €</h4>
        <h4>Lowest Foil Price : @Model.mkmProduct.priceGuide.LOWFOIL €</h4>
        <h4>Price Trend : @Model.mkmProduct.priceGuide.TREND €</h4>
    </div>     
</div>
<br />
<div class="col-lg-12">
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.CardId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

MTGWatcher/Views/Cards/Edit.cshtml
@model MTGWatcher.Models.Card

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Card</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CardId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cmc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cmc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cmc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MTGWatcher/Views/Cards/Index.cshtml
@model MTGWatcher.Models.CardListViewModel
@{
    ViewBag.Title = "Index";
}
@using System.Text.RegularExpressions
<div class="col-lg-12">
   

    @using (Html.BeginForm("RefreshCards", "Cards", FormMethod.Get, new { @role = "form", @id = "cardRefresh" }))
    {
        <input type="hidden" name="param" value="" />
        <input class="btn btn-default" id="btnSubmit" type="submit" value="Refresh Cards" />
       
    }
    @using (Html.BeginForm("RefreshSets", "Cards", FormMethod.Post, new { @role = "form", @id = "setRefresh" }))
    {
        <input type="hidden" name="param" value="" />
        <input class="btn btn-default" id="btnSubmit" type="submit" value="Refresh Sets" />
     
    }
    <div id="progressBar" class="progress" hidden>
        <div id="bar" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
            <span class="sr-only"></span>
        </div>
    </div>
    @using (Html.BeginForm("Index", "Cards", FormMethod.Post, new { @class = "form-inline", @role = "form", @id = "CardsSearchForm" }))
    {
        <div class="row">
            <div class="col-lg-6">
                <div class="input-group">
                    <input type="text" name="cardSearch" id="cardSearch" class="form-control" placeholder="Search for a card...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                    </span>
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
        @Html.HiddenFor(m => m.Page)
        @Html.HiddenFor(m => m.SortField)
        @Html.HiddenFor(m => m.SortDir)
        @Html.HiddenFor(m => m.PageSize)
        @Html.HiddenFor(m => m.ResultCount)
        <div class="panel panel-default" id="panelResults">
            <div class="panel-heading" style="padding: 5px 15px; vertical-align: middle;">
                <h4 class="panel-title" style="display: inline-block; vertical-align: middle; width: 100%;">
                    <span class="form-group input-group-sm pull-right">
                        &nbsp;Items per page&nbsp;
                        @Html.DropDownListFor(m => m.PageSize, new MultiSelectList(new List<int>() { 25, 50, 100, 500 }), new { @class = "form-control" })
                    </span>Results <i>(<span id="nbResult">@Model.ResultCount</span>)</i>
                </h4>
            </div>
            <div id="collapseResults" class="panel-collapse collapse in">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="grid">
                                @{
                                    var grid = new WebGrid(canPage: true, canSort: true, defaultSort: "", rowsPerPage: Model.PageSize, pageFieldName: "Page", sortDirectionFieldName: "SortDir", sortFieldName: "SortField");
                                    grid.Bind(Model.Results, autoSortAndPage: true, rowCount: Model.ResultCount);

                                    var columns = new List<WebGridColumn>();

                                    columns.Add(grid.Column("Name", format: @<text> <a href="/Cards/Details/@(((MTGWatcher.Models.Card)((WebGridRow)item).Value).CardId)">@(((MTGWatcher.Models.Card)((WebGridRow)item).Value).Name)</a></text>));
                                    columns.Add(grid.Column("ManaCost", format: (item) => {

                                        var rgx = new Regex(@"\{*\}*");
                                        var parsed = rgx.Replace(((MTGWatcher.Models.Card)((WebGridRow)item).Value).ManaCost??"", "");
                                        var array = parsed.ToCharArray();
                                        var tmpHtml = "";
                                        foreach (var mana in array)
                                        {
                                            tmpHtml+=string.Format("<object type='image/svg+xml' data='../Content/Symbols/{0}.svg' width='16' height='16'></object>", mana);
                                        }

                                        return new HtmlString(tmpHtml);
                                    }));

                                    columns.Add(grid.Column("PlainTypes", "Types"));
                                    columns.Add(grid.Column("PowerThoughness", "Power"));
                                    /*columns.Add(grid.Column("Rarity", format: (item) => {

                                        return new HtmlString(string.Format("<b class='gradient-{0}'>{1}</b>",((MTGWatcher.Models.Card)((WebGridRow)item).Value).Rarity.ToLower(), ((MTGWatcher.Models.Card)((WebGridRow)item).Value).Rarity));
                                    }));*/

                                   @grid.GetHtml(htmlAttributes: new { id = "CardList" }, tableStyle: "table-striped table-hover table-bordered", columns: columns)
                                    if (Model.ResultCount > Model.PageSize)
                                    {
                                        @grid.PagerList(WebGridPagerModes.FirstLast | WebGridPagerModes.Numeric, paginationStyle: "pagination paginationlist pagination-md pull-right")
                                    }
                                }
                                @Html.Hidden("dir", grid.SortDirection)
                                @Html.Hidden("col", grid.SortColumn)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
}
</div>
<style>
    .ui-autocomplete{
        background-color:white;
        border:solid 2px;
        overflow:auto;
        max-height:300px;
    }
     .ui-autocomplete li{
         list-style-type: none;
         left:0;   
    }
    .ui-autocomplete li:hover{
         background-color:#f5f5f5;
         list-style-type:circle;        
    }
</style>
<script>
    var myRoutine;

    function UpdateProgressBar() {

        $.get("/Cards/RefreshProgress", function (response, status) {
                
            var newprogress = response.data * 100;
            console.log(newprogress);
            if (newprogress == 100) clearInterval(myRoutine);
            $("#bar").attr('aria-valuenow', newprogress).css('width', newprogress);
        });

    }

    $(document).ready(function () {
        $('#cardSearch').autocomplete({
            source: '@Url.Action("AutoComplete")'
        });

        jQuery.ui.autocomplete.prototype._resizeMenu = function () {
            var ul = this.menu.element;
            ul.outerWidth(this.element.outerWidth());
        }
        /*
        $('#cardRefresh').submit(function () {

            $("#progressBar").show();
            myRoutine = setInterval(UpdateProgressBar, 1000);
               
        });*/

        $('#setRefresh').submit(function () {

            $("#progressBar").show();
            myRoutine = setInterval(UpdateProgressBar, 1000);
        });           

    })

    function GenerateManacost(code) {

        var mana = code.replace(/\{*\}*/gi, "").split("");

            
    }

</script>